-- To enable automatically load for his file on startup to create the database schema change this file nome to 'schema.sql'
-- And configure jpa spring property 'ddl-auto' => spring.jpa.hibernate.ddl-auto=none
